version: '3'

services:
  queue:
    image: webcenter/activemq
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
